### ISSUE TITLE
AttributeError: 'AdvancedBrowser' object has no attribute '_previewBoth'

### ISSUE THREAD

**Issue by gajewsk2** [glutanimate/advanced-previewer#2]
Installed and got this right away, the version on the addon store give this: 

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "anki\hooks.py", line 55, in repl
  File "aqt\browser.py", line 1005, in onTogglePreview
  File "C:\Users\Micah\Documents\Anki\addons\_Editor_fontsize.py", line 984, in _openPreview
    self._renderPreview(True)
  File "anki\hooks.py", line 55, in repl
  File "C:\Users\Micah\Documents\Anki\addons\advanced_previewer\previewer.py", line 298, in renderPreview
    if cardChanged and not self._previewBoth:
AttributeError: 'AdvancedBrowser' object has no attribute '_previewBoth'

The beta version from releases on github gives:
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "anki\hooks.py", line 55, in repl
  File "aqt\browser.py", line 1005, in onTogglePreview
  File "C:\Users\Micah\Documents\Anki\addons\_Editor_fontsize.py", line 984, in _openPreview
    self._renderPreview(True)
  File "anki\hooks.py", line 55, in repl
  File "C:\Users\Micah\Documents\Anki\addons\advanced_previewer\previewer.py", line 590, in _renderPreviewWrapper
    self._previewWindow.renderPreview(cardChanged)
AttributeError: 'QDialog' object has no attribute 'renderPreview'

I'm on windows 10, anki 2.0.41

**Comment by glutanimate** [comment]
This is a compatibility issue with the Editor fontsize add-on, so I'm afraid there's not much that I can do. With the latest GitHub release Advanced Previewer now uses a Previewer class which can be modified by third-party add-ons (for an example see [here](https://github.com/glutanimate/anki-addons-misc/blob/master/anki-previewer-tagbrowser.py)). So in theory it should be possible to make the fontsize add-on compatible with Advanced Previewer now.

**Comment by glutanimate** [comment]
I have updated the add-on description to notify users of this incompatibility, but outside of that I don't think there's much else I can do, so I will be closing this for now.
